# 🛰️ SonarQube Project Configuration
sonar.projectKey=GauravSahu2_SAMOS-Secure-Advanced-MLOps-Orchestration-System
sonar.organization=gauravSahu2
sonar.projectName=SAMOS: Secure Advanced MLOps & Orchestration System
sonar.projectVersion=1.1.0
sonar.sources=.
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/node_modules/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
sonar.host.url=https://sonarcloud.io
