import os
import re

def generate_technical_reference() -> None:
    """Phase 25: Meta-Documentation - Automated Reference Generator."""
    print("📚 Phase 25: Generating Technical Reference Guide...")
    
    docs = ["# 📖 Technical Reference: The MLOps Universe\n"]
    docs.append("This document is auto-generated by `src/sre/docs_gen.py`.\n")
    
    for root, _dirs, files in os.walk("src"):
        for file in files:
            if file.endswith(".py"):
                path = os.path.join(root, file)
                with open(path, "r") as f:
                    content = f.read()
                    # Extract Phase and Docstring
                    phase = re.search(r"Phase \d+", content)
                    docstring = re.search(r'"""(.*?)"""', content, re.DOTALL)
                    
                    docs.append(f"### 📄 {file}")
                    docs.append(f"- **Path**: `{path}`")
                    if phase:
                        docs.append(f"- **Module**: `{phase.group(0)}`")
                    if docstring:
                        docs.append(f"- **Description**: {docstring.group(1).strip()}")
                    docs.append("\n---\n")
                    
    with open("TECHNICAL_REFERENCE.md", "w") as f:
        f.write("\n".join(docs))
        
    print("✅ Technical Reference generated: TECHNICAL_REFERENCE.md")

if __name__ == "__main__":
    generate_technical_reference()
